export const products = [
    {
        id: 1,
        name: 'Apple Watch',
        category: 'Wearables',
        price: 299,
        inStock: true,
        fromDate: new Date('2026-01-01'),
        toDate: new Date('2026-06-30'),
    },
    {
        id: 2,
        name: 'MacBook Pro',
        category: 'Laptops',
        price: 1999,
        inStock: false,
        fromDate: new Date('2026-02-01'),
        toDate: new Date('2026-07-31'),
    },
    { 
        id: 3, 
        name: 'iPhone 13', 
        category: 'Phones', 
        price: 999, 
        inStock: true,
        fromDate: new Date('2026-03-01'),
        toDate: new Date('2026-08-31'),
    },
    {
        id: 4,
        name: 'iPad Air',
        category: 'Tablets',
        price: 599,
        inStock: true,
        fromDate: new Date('2026-04-01'),
        toDate: new Date('2026-09-30'),
    },
    {
        id: 5,
        name: 'AirPods Pro',
        category: 'Accessories',
        price: 249,
        inStock: true,
        fromDate: new Date('2026-05-01'),
        toDate: new Date('2026-10-31'),
    },
    {
        id: 6,
        name: 'Apple TV',
        category: 'Electronics',
        price: 199,
        inStock: false,
        fromDate: new Date('2026-06-01'),
        toDate: new Date('2026-11-30'),
    },
    {
        id: 7,
        name: 'Mac Mini',
        category: 'Computers',
        price: 699,
        inStock: true,
        fromDate: new Date('2026-07-01'),
        toDate: new Date('2026-12-31'),
    },
    {
        id: 8,
        name: 'Magic Keyboard',
        category: 'Accessories',
        price: 349,
        inStock: true,
        fromDate: new Date('2026-08-01'),
        toDate: new Date('2027-02-28'),
    },
    {
        id: 9,
        name: 'iMac',
        category: 'Computers',
        price: 1499,
        inStock: false,
        fromDate: new Date('2026-09-01'),
        toDate: new Date('2027-03-31'),
    },
    {
        id: 10,
        name: 'Apple Pencil',
        category: 'Accessories',
        price: 129,
        inStock: true,
        fromDate: new Date('2026-10-01'),
        toDate: new Date('2027-04-30'),
    },
];
